apiVersion: v1
kind: Service
metadata:
  name: mysql-mastersvc
  namespace: mulhome-mysql
spec:
  #type: ClusterIP
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
